QuestionMark/Controllers/HomeController.cs
using QuestionMark.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuestionMark.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext _db;

        public HomeController()
        {
            _db = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            List<Question> model;

            model = _db.Questions.OrderByDescending(m => m.PublishedAt).Take(100).ToList();

            return View(model);
        }
    }
}

QuestionMark/Controllers/PartialsController.cs
using QuestionMark.Models;
using QuestionMark.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuestionMark.Controllers
{
    public class PartialsController : Controller
    {
        // GET: Partials
        [AllowAnonymous]
        public PartialViewResult UserInformation(string email)
        {
            UserInformationViewModel model = new UserInformationViewModel();

            using (var db = new ApplicationDbContext())
            {
                var user = db.Users.FirstOrDefault(m => m.Email.Equals(email));

                if (user != null)
                {
                    model.Email = user.Email;
                    model.Name = user.Name;
                    model.EnrollmentNumber = user.EnrollmentNumber;
                }
            }

            return PartialView("_UserInformation", model);
        }

        public PartialViewResult NewQuestion()
        {
            Question question = new Question();

            using (var db = new ApplicationDbContext())
            {
                ViewBag.TopicID = new SelectList(db.Topics.ToList(), "TopicID", "Title");
                question.UserID = db.Users.FirstOrDefault(m => m.Email.Equals(User.Identity.Name)).Id;
            }

            return PartialView("_NewQuestion", question);
        }

        public PartialViewResult AnswerQuestion()
        {
            return PartialView("_AnswerQuestion");
        }

        public PartialViewResult Questions()
        {
            List<Question> model;
            using (var db = new ApplicationDbContext())
            {
                model = db.Questions
                    .Include(p => p.Topic)
                    .Include(p => p.User)
                    .ToList();
            }

            return PartialView("_Questions", model);
        }
    }
}

QuestionMark/Views/Home/Index.cshtml
@{

    ViewBag.Title = "Home Page";
}

@if (User.Identity.IsAuthenticated)
{
    @Html.Action("NewQuestion", "Partials")

    if (User.IsInRole("Administrator"))
    {
        <script>
           function requestQuestion(id) {
                $.ajax("/questions/getjson/" + id,
                    {
                        type: "GET"
                    }).success(function (data) {
                        $('#questionToAnswer').html(data.Content);
                        $('#questionIdToAnswer').val(data.QuestionID);
                    }).error(function () {
                        console.log("Erro!");
                    });
            }

            function answerQuestion(id, answer) {
                $.ajax("/questions/answerjson",
                    {
                        type: "POST",
                        data: {
                            questionid: id,
                            answer: answer
                        }
                    }).success(function (data) {
                        console.log("Question answered");
                    }).error(function () {
                        console.log("Question not answered");
                    });
            }
        </script>

        @Html.Action("AnswerQuestion", "Partials")
    }
}

@Html.Action("Questions", "Partials")

@section scripts
{
<script>
    $('.grid').masonry({
        itemSelector: '.grid-item',
    });

    $(".flip").hover(function () {
        console.log("HOOOVEEEERRR chegou aqui");
        $(this).find(".card").toggleClass("flipped");
        return false;
    });
</script> 
}